### ISSUE TITLE
Is UBI-Micro part of RH container ecosystem?

### ISSUE THREAD

**Issue by ferrx** [fatherlinux/ubi-micro#6]
Is it on the roadmap? I only see standard, -minimal, and -init at https://catalog.redhat.com/software/containers/search?q=ubi7&p=1

Not seeing much info on -micro. Is there a write-up somewhere? Does this use microdnf like -minimal?

**Comment by glinkaf** [comment]
Hi, is the any update or information available regarding this question?

**Comment by fatherlinux** [comment]
Sorry, I have no idea why, but I never got a message about these comments. UBI micro is targeted to be released as part of RHEL in 8.4 which should be May 2021ish. Until then, feel free to build this yourself. This creates a "real RHEL/UBI" image that is no different than a scratch image from a support perspective.
